users/urls.py
from django.urls import path
from users import views

urlpatterns = [
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('', views.home, name='home'),

]

workspace/urls.py
"""workspace URL Configuration
"""
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('users.urls', 'users'), namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cards/models.py
from typing_extensions import Required
from django.contrib.auth.models import User
from django.db import models
from django.db.models.base import Model
from django.db.models.deletion import CASCADE

# Create your models here.

class Card(models.Model):
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    front = models.CharField(max_length=150, Required=True)
    back = models.CharField(max_length=400, Required=True)
    deck_name = models.CharField(max_length=100, Required=True)
    category = models.CharField(max_length=100, Required=True)
    active_deck = models.BooleanField(default=True)
    favorite = models.BooleanField(default=False)
    tag = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.front

users/models.py
# Django imports
from django.db import models
# Accessing to the django built-in user model
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE

# Creating the profile model
class Profile(models.Model):
    """
    It creates the model profile on the database, 
    using a oneToOne field to the existent Django user model
    """
    user = models.OneToOneField(User,on_delete=CASCADE)
    website = models.URLField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)
    picture = models.ImageField(upload_to='users/picture', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username
    

users/forms.py
# Django
from django import forms

# Models
from django.contrib.auth.models import User
from users.models import Profile

class SignupForm(forms.Form):
    """
    Signup form
        Doc: [https://docs.djangoproject.com/en/2.0/ref/forms/widgets/, https://docs.djangoproject.com/en/2.0/ref/forms/fields/]"""
    
    username = forms.CharField(label=False,min_length=4, max_length=50, widget = forms.TextInput(
                                attrs={'placeholder':'Username','class': 'form-control','required': True}))
    password = forms.CharField(label=False,max_length=70, widget=forms.PasswordInput(
                                attrs={'placeholder':'Password','class': 'form-control','required': True}))
    password_confirmation = forms.CharField(label=False,max_length=70, widget=forms.PasswordInput(
                                attrs={'placeholder':'Password confirmation','class': 'form-control','required': True}))        

    first_name = forms.CharField(label=False,min_length=2, max_length=50, widget = forms.TextInput(
                                attrs={'placeholder':'First name','class': 'form-control','required': True}))
    last_name = forms.CharField(label=False,min_length=2, max_length=50, widget = forms.TextInput(
                                attrs={'placeholder':'Last name','class': 'form-control','required': True}))

    email = forms.CharField(label=False,min_length=6, max_length=70, widget=forms.EmailInput(
                                attrs={'placeholder':'Email','class': 'form-control','required': True}))

    def clean_username(self):
        """
            Username must be unique.
            Doc: https://docs.djangoproject.com/en/2.0/ref/forms/validation/
        """
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in used.')
        return username
    def clean(self):
        """
            Verify password confirmation
        """
        data = super().clean()
        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Password do not match.')
        return data
    def save(self):
        """Create user and profile"""
        data = self.cleaned_data
        data.pop('password_confirmation')
        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()  

cards/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import redirect,render
# Django
from django.urls import reverse_lazy
from django.contrib.auth import logout, views as auth_views
from django.contrib.auth.decorators import login_required
from django.views.generic import FormView
from users.forms import SignupForm
# Importing forms


# Create your views here.
class SignupView(FormView):
    """Users sign up class view."""

    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')
    # To save the data
    def form_valid(self, form):
        """Save form data."""
        form.save()
        return super().form_valid(form)

@login_required
def home(request):
    return render(request=request, template_name='users/home.html', context={})

class LoginView(auth_views.LoginView):
    """Login view."""
    template_name = 'users/login.html'
    
@login_required
def logout_view(request):
    """Loging out """
    logout(request)
    return redirect('users:logout')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}


    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body>

    {% include "nav.html" %}

    <div class="container mt-5">
        {% block container %}
        {% endblock%}
    </div>

</body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg sticky-top" id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="">
            <p height="45" class="d-inline-block align-top">Workspace</p>
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a href="">
                        {% if request.user.profile.picture %}
                            <img src="{{ request.user.profile.picture.url }}" height="35" class="d-inline-block align-top rounded-circle"/>
                        {% else %}
                            <img src="{% static 'img/default-profile.png' %}" height="35" class="d-inline-block align-top rounded-circle"/>
                        {% endif %}
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'users:logout'%}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    

</head>
<body class="h-100">
    <nav class="navbar navbar-expand-lg sticky-top" id="main-navbar">
        <div class="container">
    
            <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="">
                <p height="45" class="d-inline-block align-top">Workspace</p>
            </a>
    
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav mr-auto">
    
                </ul>
            </div>
        </div>
    </nav>

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">        

                <img src="" class="img-fluid rounded mx-auto d-block 
pb-4" style="max-width: 60%;">

                {% block container %}{% endblock%}

            </div>
        </div>
    </div>

</body>
</html>

templates/users/home.html
{% extends "base.html" %}
{% block head_content %}
    <title>Workspace</title>
{% endblock %}

{% block container %}

{% endblock %}

templates/users/login.html
{% extends "users/base.html" %}
{% block head_content %}
    <title>Registrate</title>
{% endblock %}

{% block container %}
    {% if form.error %}
        <p class="alert alert-danger">Your username and password doesn't match</p>
    {% endif %}
    <form method="POST" action="{% url 'users:login' %}">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" placeholder="Username" name="username" class="form-control">
        </div>
         <div class="form-group">
            <input type="password" placeholder="Password" name="password" class="form-control">      
        </div>
        <button class="btn btn-primary btn-block mt-5" type="submit">Entrar</button>
    </form>
    <p class="mt-4">Aún no estás registrado? <a href="">Registrate aquí.</a></p>
{% endblock %}

templates/users/signup.html
{% extends 'users/base.html' %}
{% block head_content %}
    <title>Regirstarse</title>
{% endblock head_content %}

{% block container %}

    <form action="{% url 'users:signup' %}" method="post">
    {% csrf_token %} <!--Siempre que se crea un formulario hay que crear el csrf-->

    {{ form.as_p}}

    <button class="btn btn-primary btn-block mt-5" type="submit">Registrarse!</button>

    </form>
{% endblock container %}